version: '3'

services:
  mongo:
    build:
      context: mongo/
    ports:
      - "27017:27017"
  redis:
    image: redis
  web:
    build:
      context: web/
    volumes:
            - ./web/local_settings.py:/www/sefaria/local_settings.py
            - ./web/config:/www/sefaria/config
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - redis
